name: unite_india_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0' # Updated for better compatibility

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  geolocator: ^13.0.1
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true