// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrPqKR_gRz8cUNgxJG352wH4_09IY8VY',
    appId: '1:1049249597566:web:c9a75c1ce8fc04bd3f302f',
    messagingSenderId: '1049249597566',
    projectId: 'uniteindia-pratap',
    authDomain: 'uniteindia-pratap.firebaseapp.com',
    storageBucket: 'uniteindia-pratap.firebasestorage.app',
    measurementId: 'G-7BSQ67JFMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aiAYJW_8pQ99Xj2coOgz96ZtTmRgBkk',
    appId: '1:1049249597566:android:72af72d80bc6f6923f302f',
    messagingSenderId: '1049249597566',
    projectId: 'uniteindia-pratap',
    storageBucket: 'uniteindia-pratap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVPKY1fcrBgar4pwwgt6BjV78xU1GyRvU',
    appId: '1:1049249597566:ios:1ab1755d0cdf714c3f302f',
    messagingSenderId: '1049249597566',
    projectId: 'uniteindia-pratap',
    storageBucket: 'uniteindia-pratap.firebasestorage.app',
    iosBundleId: 'com.example.uniteIndiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVPKY1fcrBgar4pwwgt6BjV78xU1GyRvU',
    appId: '1:1049249597566:ios:1ab1755d0cdf714c3f302f',
    messagingSenderId: '1049249597566',
    projectId: 'uniteindia-pratap',
    storageBucket: 'uniteindia-pratap.firebasestorage.app',
    iosBundleId: 'com.example.uniteIndiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPrPqKR_gRz8cUNgxJG352wH4_09IY8VY',
    appId: '1:1049249597566:web:3dbb6f077f522d403f302f',
    messagingSenderId: '1049249597566',
    projectId: 'uniteindia-pratap',
    authDomain: 'uniteindia-pratap.firebaseapp.com',
    storageBucket: 'uniteindia-pratap.firebasestorage.app',
    measurementId: 'G-7QYLDG69GE',
  );
}
